image: registry.gitlab.com/tseenshe/stack2cabal:8.4.4

# TODO matrix build
# https://docs.gitlab.com/ce/ci/yaml/README.html

build_job:
  stage: build
  script:
    - cabal v2-build all
    - for TEST in tests/* ; do
        LC_ALL=C cabal v2-run stackage-to-hackage -- ${TEST}/stack.yaml ;
      done
    - git diff tests
    - STACK2CABAL=$(cabal v2-exec -- which stack2cabal) &&
      pushd tests/hpack &&
      LC_ALL=C $STACK2CABAL &&
      popd &&
      git diff tests
