image: registry.gitlab.com/tseenshe/stackage-to-hackage:8.4.4

# TODO matrix build
# https://docs.gitlab.com/ce/ci/yaml/README.html

build_job:
  stage: build
  script:
    - cabal v2-build
    - for TEST in tests/* ; do
        LC_ALL=C cabal v2-run stackage-to-hackage -- ${TEST}/stack.yaml ;
      done
    - git diff tests
