name: Docker build

on:
  create:
    tags:
      - 'v*'
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Branch name
        id: branch_name
        run: |
          echo ${{ github.ref }}
          echo ${{ github.event_name }}
          echo ::set-env name=GITHUB_REF::${GITHUB_REF}
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
        shell: bash

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - if: github.event_name == 'pull_request'
        run: echo ::set-env name=TAGS::hasufell/stack2cabal:${GITHUB_SHA}
        shell: bash

      - if: github.event_name == 'push'
        run: echo ::set-env name=TAGS::hasufell/stack2cabal:latest,hasufell/stack2cabal:${GITHUB_SHA}
        shell: bash

      - if: github.event_name == 'create' && startsWith(github.ref, 'refs/tags/v')
        run: echo ::set-env name=TAGS::hasufell/stack2cabal:${{ steps.branch_name.outputs.SOURCE_TAG }}
        shell: bash

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ env.TAGS }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
